# db config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fuel_management_system
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#  naming strategy config
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  kafka producer config
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer